/**
 * NATS subjects for the track processing pipeline.
 * Covers ingestion, AI stages, transcoding, and HLS persistence.
 */
export enum TrackEvent {
  /** Upload received by Soundgarden. */
  UploadReceived = 'track.upload.received',
  /** Upload validated by Soundgarden. */
  UploadValidated = 'track.upload.validated',
  /** Upload stored by Soundgarden. */
  UploadStored = 'track.upload.stored',
  /** Upload completed and ready for downstream processing. */
  Uploaded = 'track.uploaded',
  /** Upload failed during ingestion. */
  UploadFailed = 'track.upload.failed',
  /** Fingerprint generated by Petrified. */
  PetrifiedGenerated = 'track.petrified.generated',
  /** Song identified by Petrified. */
  PetrifiedSongFound = 'track.petrified.song.found',
  /** No song match found by Petrified. */
  PetrifiedSongUnknown = 'track.petrified.song.unknown',
  /** Existing fingerprint match detected by Petrified. */
  PetrifiedDetected = 'track.petrified.detected',
  /** Fingerprinting failed. */
  PetrifiedFailed = 'track.petrified.failed',
  /** Duplicate track detected. */
  DuplicateDetected = 'track.duplicate.detected',
  /** Transcription started by Fort Minor. */
  FortMinorStarted = 'track.fort-minor.started',
  /** Transcription completed by Fort Minor. */
  FortMinorCompleted = 'track.fort-minor.completed',
  /** Transcription failed. */
  FortMinorFailed = 'track.fort-minor.failed',
  /** Stereo reasoning started. */
  StereoStarted = 'track.stereo.started',
  /** Track approved by Stereo. */
  Approved = 'track.approved',
  /** Track rejected by Stereo. */
  Rejected = 'track.rejected',
  /** Stereo reasoning failed. */
  StereoFailed = 'track.stereo.failed',
  /** Transcoding started by Mockingbird. */
  TranscodingStarted = 'track.transcoding.started',
  /** Transcoding completed by Mockingbird. */
  TranscodingCompleted = 'track.transcoding.completed',
  /** Transcoding failed. */
  TranscodingFailed = 'track.transcoding.failed',
  /** HLS package generated by Mockingbird. */
  HlsGenerated = 'track.hls.generated',
  /** HLS package persisted by Hybrid Storage. */
  HlsStored = 'track.hls.stored',
  /** HLS generation or persistence failed. */
  HlsFailed = 'track.hls.failed'
}
