version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mongo-auth
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ['CMD', 'mongosh', '--quiet', '--eval', 'db.adminCommand("ping").ok']
      interval: 10s
      timeout: 5s
      retries: 10

  authority:
    build:
      context: .
      dockerfile: ./domain/identity/authority/Dockerfile
    container_name: authority
    ports:
      - '7000:7000'
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - domain/identity/authority/.env
    restart: unless-stopped

  soundgarden:
    build:
      context: .
      dockerfile: ./domain/ingestion/soundgarden/Dockerfile
    container_name: soundgarden
    ports:
      - '7100:7100'
    env_file:
      - domain/ingestion/soundgarden/.env.template
    restart: unless-stopped

  pulse:
    build:
      context: .
      dockerfile: ./apps/pulse/Dockerfile
    container_name: pulse
    ports:
      - '3000:3000'
    depends_on:
      authority:
        condition: service_started
    environment:
      PORT: '3000'
      BFF_BASE_URL: 'http://authority:7000/auth'
      BFF_API_TIMEOUT_MS: '10000'
    restart: unless-stopped

volumes:
  mongo_data:
